- name: Create mount directories
  include_role:
    name: dockermounts
    tasks_from: main
  vars:
    mounts:
    - { source: portainer/ }

- name: Deploy Docker container
  include_role:
    name: dockercontainer
    tasks_from: default
  vars:
    container_basename: "portainer"
    container_image: "portainer/portainer-ce"
    container_tag: "{{ portainer.version }}"
    exposed_ports: "9000:9000"
    labels:
      diun.enable: "true"
      diun.watch_repo: "true"
      diun.include_tags: "^\\d+(\\.\\d+)+(\\-alpine)?$"
      diun.max_tags: "10"
    mounts:
    - { source: /var/run/docker.sock, target: /var/run/docker.sock, read_only: "no", type: bind }
    - { source: /dockermnt/portainer, target: /data,                read_only: "no", type: bind }
